name = "Coulter"
uuid = "a3d351dc-6fd6-5e2a-8264-8c30d37eaa59"
authors = ["Tamas Nagy <github@tamasnagy.com>"]
version = "0.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataStructures = "0.17, 0.18"
Dates = "1"
Distributions = "0.22, 0.23, 0.24, 0.25"
FileIO = "1"
KernelDensity = "0.5, 0.6"
StatsBase = "0.32, 0.33, 0.34"
julia = "1"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs"]
